DROP SEQUENCE SQ_ARTISTA_GERAL;
CREATE SEQUENCE SQ_ARTISTA_GERAL
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_CLIENTE;
CREATE SEQUENCE SQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_ASSENTO;
CREATE SEQUENCE SQ_ASSENTO
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_CONTAS;
CREATE SEQUENCE SQ_CONTAS
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_AGENTE;
CREATE SEQUENCE SQ_AGENTE
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_DESCONTOS;
CREATE SEQUENCE SQ_DESCONTOS
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_DATA_CONTA;
CREATE SEQUENCE SQ_DATA_CONTA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_ENDERECO;
CREATE SEQUENCE SQ_ENDERECO
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_EVENTO;
CREATE SEQUENCE SQ_EVENTO
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_EVENTO_INGRESSO;
CREATE SEQUENCE SQ_EVENTO_INGRESSO
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_FUNCIONARIO;
CREATE SEQUENCE SQ_FUNCIONARIO
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_ITEM_VENDA;
CREATE SEQUENCE SQ_ITEM_VENDA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_LOGIN;
CREATE SEQUENCE SQ_LOGIN
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_PAGAMENTO;
CREATE SEQUENCE SQ_PAGAMENTO
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_PERGUNTASECRETA;
CREATE SEQUENCE SQ_PERGUNTASECRETA
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_REDESOCIAL;
CREATE SEQUENCE SQ_REDESOCIAL
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_VENDA;
CREATE SEQUENCE SQ_VENDA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_PESSOA;
CREATE SEQUENCE SQ_PESSOA
START WITH 2
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_FORMA_PAGAMENTO;
CREATE SEQUENCE SQ_FORMA_PAGAMENTO
START WITH 6
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_FUNCAO;
CREATE SEQUENCE SQ_FUNCAO
START WITH 5
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_LOG;
CREATE SEQUENCE SQ_LOG
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_LOG_ALTER;
CREATE SEQUENCE SQ_LOG_ALTER
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_LOG_INSER;
CREATE SEQUENCE SQ_LOG_INSER
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_LOG_EXCL;
CREATE SEQUENCE SQ_LOG_EXCL
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_CANCELA_VENDA;
CREATE SEQUENCE SQ_CANCELA_VENDA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_DETALHE_CONTA;
CREATE SEQUENCE SQ_DETALHE_CONTA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

DROP SEQUENCE SQ_DETALHE_CV;
CREATE SEQUENCE SQ_DETALHE_CV
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;