/* 
            COMEDY HOUSE
            
    Tema: CASA DE SHOW DE STAND-UP
    
    Turma: INF3AM
    
    Equipe 5: Arthur Porto                 01
              Diego Gomes                  07
              Gabriel Leandro              11
              Lucas Camargo                19
              Marcos Santos                26
           
*/
DROP USER TCC_SHOW CASCADE;

CREATE USER TCC_SHOW IDENTIFIED BY "1234";

GRANT ALL PRIVILEGES to TCC_SHOW;


--DROP TABLE TCC_SHOW.TB_TIPO_PESSOA;
CREATE TABLE TCC_SHOW.TB_TIPO_PESSOA(
    ID_TIPO_PESSOA INTEGER NOT NULL,
    TIPO_PESSOA VARCHAR2(12) NOT NULL,
    
    CONSTRAINT TB_TIPO_PESSOA_PK PRIMARY KEY (ID_TIPO_PESSOA)
);

--DROP TABLE TCC_SHOW.TB_PESSOA;
CREATE TABLE TCC_SHOW.TB_PESSOA(
    ID_PESSOA INTEGER NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    DATA_NASC DATE NOT NULL,
    SEXO VARCHAR2(9) NOT NULL,
    ATIVO NUMBER(1) NOT NULL,
    ID_TIPO_PESSOA INTEGER NOT NULL,
    DATA_CRIACAO DATE,
    
    CONSTRAINT TB_PESSOA_PK PRIMARY KEY (ID_PESSOA),
    CONSTRAINT TB_TIPO_PESSOA_FK FOREIGN KEY(ID_TIPO_PESSOA)
    REFERENCES TCC_SHOW.TB_TIPO_PESSOA(ID_TIPO_PESSOA)
);

--DROP TABLE TCC_SHOW.TB_CEP;
CREATE TABLE TCC_SHOW.TB_CEP(
    CEP VARCHAR2(8) NOT NULL,
    UF VARCHAR2(2),
    DESCRICAO VARCHAR2(256),
    CIDADE VARCHAR2(27),
    BAIRRO VARCHAR2(128),
    
    CONSTRAINT TB_CEP_PK PRIMARY KEY (CEP) ENABLE
);

--DROP TABLE TCC_SHOW.TB_ENDERECO;
CREATE TABLE TCC_SHOW.TB_ENDERECO(
    ID_ENDERECO INTEGER NOT NULL,
    CEP VARCHAR2(8) NOT NULL,
    NUMERO NUMBER(6),
    COMPLEMENTO VARCHAR2(120),
    
    CONSTRAINT TB_ENDERECO_PK PRIMARY KEY (ID_ENDERECO),
    CONSTRAINT TB_CEP_FK FOREIGN KEY(CEP)
    REFERENCES TCC_SHOW.TB_CEP(CEP)
);

--DROP TABLE TCC_SHOW.TB_AGENTE;
CREATE TABLE TCC_SHOW.TB_AGENTE(
    ID_AGENTE INTEGER NOT NULL,
    ID_ENDERECO INTEGER NOT NULL,
    TELEFONE VARCHAR2(14),
    TIPO_PESSOA VARCHAR2(8) NOT NULL,
    DOCUMENTO VARCHAR2(18),
    EMAIL VARCHAR2(120),
    NOME_PRINCIPAL VARCHAR2(120) NOT NULL,--NOME FANTASIA/NOME CIVIL
    NOME_SECUNDARIO VARCHAR2(120), --RAZÃO SOCIAL/NOME SOCIAL
    ATIVO NUMBER(1),
    DATA_CRIACAO DATE,
    CONSTRAINT DOCUMENTO_AGENTE_UN UNIQUE (DOCUMENTO),
    CONSTRAINT TB_AGENTE_PK PRIMARY KEY (ID_AGENTE) ENABLE,
    CONSTRAINT TB_AGENTE_ENDERECO_FK FOREIGN KEY(ID_ENDERECO)
    REFERENCES TCC_SHOW.TB_ENDERECO(ID_ENDERECO)
);

--DROP TABLE TCC_SHOW.TB_REDESOCIAL;
CREATE TABLE TCC_SHOW.TB_REDESOCIAL(
    ID_REDESOCIAL INTEGER NOT NULL,
    FACEBOOK VARCHAR2(120),
    TWITTER VARCHAR2(120),
    INSTAGRAM VARCHAR2(120),
    
    CONSTRAINT TB_REDESOCIAL_PK PRIMARY KEY(ID_REDESOCIAL) ENABLE
);   

--DROP TABLE TCC_SHOW.TB_ARTISTA_GERAL;
CREATE TABLE TCC_SHOW.TB_ARTISTA_GERAL(
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    ID_REDESOCIAL INTEGER,
    ID_PESSOA INTEGER NOT NULL,
    TIPO_PAG VARCHAR2(10) NOT NULL,
    VALOR_PAG NUMBER(20,2),
    URL_IMG VARCHAR2(250),
    
    CONSTRAINT TB_ART_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TCC_SHOW.TB_PESSOA(ID_PESSOA),
     CONSTRAINT TB_REDESOCIAL_FK FOREIGN KEY (ID_REDESOCIAL)
    REFERENCES TCC_SHOW.TB_REDESOCIAL(ID_REDESOCIAL),
    CONSTRAINT TB_ARTISTA_GERAL_PK PRIMARY KEY (ID_ARTISTA_GERAL) ENABLE
);

--DROP TABLE TCC_SHOW.TB_ARTISTA;
CREATE TABLE TCC_SHOW.TB_ARTISTA(
    ID_AGENTE INTEGER NOT NULL,
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    
    CONSTRAINT TB_ARTISTA_PK PRIMARY KEY (ID_ARTISTA_GERAL, ID_AGENTE) ENABLE
);

--DROP TABLE TCC_SHOW.TB_ARTISTA_FIXO;
CREATE TABLE TCC_SHOW.TB_ARTISTA_FIXO(
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    ID_ENDERECO INTEGER NOT NULL,
    TELEFONE VARCHAR2(14),
    CPF VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(120),
    CONSTRAINT CPF_ART_FIXO_UN UNIQUE (CPF),
    CONSTRAINT TB_ARTISTA_FIXO_PK PRIMARY KEY (ID_ARTISTA_GERAL, ID_ENDERECO) ENABLE
);

--DROP TABLE TCC_SHOW.TB_FORMA_PAGAMENTO;
CREATE TABLE TCC_SHOW.TB_FORMA_PAGAMENTO(
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    FORMA_PAGAMENTO VARCHAR2(30) NOT NULL,
    
    CONSTRAINT TB_FORMA_PAGAMENTO_PK PRIMARY KEY(ID_FORMA_PAGAMENTO) ENABLE
);

--DROP TABLE TCC_SHOW.TB_DATA_CONTA;
CREATE TABLE TCC_SHOW.TB_DATA_CONTA(
    ID_DATA_CONTA INTEGER NOT NULL,
    DATA_CONTA DATE NOT NULL,
    TIPO_DATA VARCHAR(11) NOT NULL,
    
    CONSTRAINT TB_DATA_CONTA_PK PRIMARY KEY (ID_DATA_CONTA)
);

--DROP TABLE TCC_SHOW.TB_CONTAS;
CREATE TABLE TCC_SHOW.TB_CONTAS(
    ID_CONTAS INTEGER NOT NULL,
    ID_DATA_CONTA INTEGER NOT NULL,
    TIPO_CONTA VARCHAR2(15) NOT NULL,
    DATA_LANCAMENTO DATE,
    DESCRICAO VARCHAR2(220),
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    SITUACAO VARCHAR(30),
    DEPARTAMENTO VARCHAR(30),
    VALOR NUMBER(24,2) NOT NULL,
    ATIVO NUMBER(1),
    
    CONSTRAINT TB_CONTAS_PK PRIMARY KEY (ID_CONTAS),
    CONSTRAINT TB_FORMA_PAG_FK FOREIGN KEY(ID_FORMA_PAGAMENTO)
    REFERENCES TCC_SHOW.TB_FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO),
    CONSTRAINT TB_DATA_CONTA_FK FOREIGN KEY(ID_DATA_CONTA)
    REFERENCES TCC_SHOW.TB_DATA_CONTA(ID_DATA_CONTA)
);



--DROP TABLE TCC_SHOW.TB_CLIENTE;
CREATE TABLE TCC_SHOW.TB_CLIENTE(
    ID_CLIENTE INTEGER NOT NULL,
    CPF VARCHAR2(12) NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    CONSTRAINT CPF_CLIENTE_UN UNIQUE (CPF),
    CONSTRAINT TB_CLIENTE_PK PRIMARY KEY (ID_CLIENTE) ENABLE,
    CONSTRAINT TB_CLI_PESSOA_FK FOREIGN KEY(ID_PESSOA) REFERENCES 
    TCC_SHOW.TB_PESSOA(ID_PESSOA)
);

--DROP TABLE TCC_SHOW.TB_TIPO_ASSENTO;
CREATE TABLE TCC_SHOW.TB_TIPO_ASSENTO(
    ID_TIPO_ASSENTO NUMBER(4) NOT NULL,
    TIPO_ASSENTO VARCHAR2(8) NOT NULL,
    
    CONSTRAINT TB_TIPO_ASSENTO_PK PRIMARY KEY (ID_TIPO_ASSENTO) ENABLE
);

--DROP TABLE TCC_SHOW.TB_SETOR;
CREATE TABLE TCC_SHOW.TB_SETOR(
    ID_SETOR INTEGER NOT NULL,
    SETOR VARCHAR2(6),
    
    CONSTRAINT TB_SETOR_PK PRIMARY KEY (ID_SETOR) ENABLE
);

--DROP TABLE TCC_SHOW.TB_ASSENTO;
CREATE TABLE TCC_SHOW.TB_ASSENTO(
    ID_ASSENTO INTEGER NOT NULL,
    ASSENTO_NUMER NUMBER(3) NOT NULL,
    ASSENTO_FILEIRA VARCHAR2(1) NOT NULL,
    ID_TIPO_ASSENTO INTEGER NOT NULL,
    ID_SETOR INTEGER NOT NULL,
    
    CONSTRAINT TB_ASSENTO_PK PRIMARY KEY (ID_ASSENTO) ENABLE,
    CONSTRAINT TB_SETOR_FK FOREIGN KEY(ID_SETOR) REFERENCES 
    TCC_SHOW.TB_SETOR(ID_SETOR),
    CONSTRAINT TB_TIPO_ASSENTO_FK FOREIGN KEY(ID_TIPO_ASSENTO) REFERENCES 
    TCC_SHOW.TB_TIPO_ASSENTO(ID_TIPO_ASSENTO)
);


--DROP TABLE TCC_SHOW.TB_ASSENTO_CLI;
CREATE TABLE TCC_SHOW.TB_ASSENTO_CLI(
    ID_ASSENTO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    
    CONSTRAINT TB_ASSENTO_CLI_PK PRIMARY KEY (ID_ASSENTO,ID_CLIENTE) ENABLE
);

--DROP TABLE TCC_SHOW.TB_EVENTO;
CREATE TABLE TCC_SHOW.TB_EVENTO(
    ID_EVENTO INTEGER NOT NULL,
    TITULO VARCHAR2(20),
    DATA_EVENTO DATE,
    DESCRICAO VARCHAR2(141),
    HORARIO_INICIO DATE NOT NULL,
    HORARIO_FINAL DATE NOT NULL,
    N_ARTISTAS NUMBER(3),
    ATIVO NUMBER(1) NOT NULL,
    VALOR_EVENTO NUMBER(10,2) NOT NULL,
    
    CONSTRAINT TB_EVENTO_PK PRIMARY KEY(ID_EVENTO) ENABLE
);

--DROP TABLE TCC_SHOW.TB_EVENTO_INGRESSO;
CREATE TABLE TCC_SHOW.TB_EVENTO_INGRESSO(
    ID_EI INTEGER NOT NULL,
    PRECO_TOTAL NUMBER(15,2),
    ID_EVENTO INTEGER,
    ID_PAGAMENTO INTEGER,
    DESCONTO NUMBER(10,2),
    
    CONSTRAINT TB_EVENTOINGRESSO_PK PRIMARY KEY (ID_EI) ENABLE,
    CONSTRAINT TB_EVENTOINGRESSO_FK FOREIGN KEY (ID_EI)
    REFERENCES TCC_SHOW.TB_EVENTO(ID_EVENTO)
    
);

--DROP TABLE TCC_SHOW.TB_VENDA_INGRESSO;
CREATE TABLE TCC_SHOW.TB_VENDA_INGRESSO(
    ID_VENDA INTEGER NOT NULL,
    ID_PESSOA INTEGER,
    DATAVENDA DATE,
    
    CONSTRAINT TB_VENDA_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TCC_SHOW.TB_PESSOA(ID_PESSOA),
    CONSTRAINT TB_VENDA_INGRESSO_PK PRIMARY KEY (ID_VENDA) ENABLE
);

--DROP TABLE TCC_SHOW.TB_ITEM_VENDA;
CREATE TABLE TCC_SHOW.TB_ITEM_VENDA(
    ID_ITEM_VENDA INTEGER NOT NULL,
    ID_VENDA INTEGER NOT NULL,
    ID_EI INTEGER NOT NULL,
    ID_ASSENTO INTEGER NOT NULL,
    
    CONSTRAINT TB_ITEM_VENDA_PK PRIMARY KEY (ID_ITEM_VENDA) ENABLE,
    CONSTRAINT TB_VENDA_FK FOREIGN KEY (ID_VENDA) REFERENCES TCC_SHOW.TB_VENDA_INGRESSO(ID_VENDA),
    CONSTRAINT TB_EI_FK FOREIGN KEY (ID_EI) REFERENCES TCC_SHOW.TB_EVENTO_INGRESSO(ID_EI)
);



--DROP TABLE TCC_SHOW.TB_PAGAMENTO;
CREATE TABLE TCC_SHOW.TB_PAGAMENTO(
    ID_PAGAMENTO INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    QUANTIA NUMBER(10,2) NOT NULL,
    
    CONSTRAINT TB_PAGAMENTO_PK PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT TB_PAGAMENTO_FK FOREIGN KEY(ID_PAGAMENTO) REFERENCES 
    TCC_SHOW.TB_FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO) 
);



--DROP TABLE TCC_SHOW.TB_EVENTO_ARTISTA;
CREATE TABLE TCC_SHOW.TB_EVENTO_ARTISTA(
    ID_EVENTO INTEGER NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    
    CONSTRAINT TB_EVENTO_PESSOA_PK PRIMARY KEY (ID_EVENTO,ID_PESSOA)
);

--DROP TABLE TCC_SHOW.TB_PERGUNTASECRETA;
CREATE TABLE TCC_SHOW.TB_PERGUNTASECRETA(
    ID_PERGUNTASECRETA INTEGER NOT NULL,
    DESCRICAO VARCHAR2(128),
    RESPOSTA VARCHAR2(120) NOT NULL,
    
    CONSTRAINT TB_PERGUNTASECRETA_PK PRIMARY KEY(ID_PERGUNTASECRETA) ENABLE
);

--DROP TABLE TCC_SHOW.TB_NIVELACESSO;
CREATE TABLE TCC_SHOW.TB_NIVELACESSO(
    ID_NIVELACESSO INTEGER NOT NULL,
    NIVELACESSO VARCHAR2(20) NOT NULL,
    
    CONSTRAINT TB_NIVELACESSO_PK PRIMARY KEY (ID_NIVELACESSO) ENABLE
);


--DROP TABLE TCC_SHOW.TB_LOGIN;
CREATE TABLE TCC_SHOW.TB_LOGIN(
    ID_LOGIN INTEGER NOT NULL,
    ID_NIVELACESSO INTEGER NOT NULL,
    ID_PERGUNTASECRETA INTEGER NOT NULL,
    USUARIO VARCHAR2(50) NOT NULL,
    SENHA VARCHAR2(50) NOT NULL,
    DATAULTIMOACESSO DATE,
    ID_PESSOA INTEGER NOT NULL,
    
    CONSTRAINT TB_NIVEL_ACESSO_FK FOREIGN KEY (ID_NIVELACESSO)
    REFERENCES TCC_SHOW.TB_NIVELACESSO(ID_NIVELACESSO),
    CONSTRAINT TB_PERGUNTASECRETA_FK FOREIGN KEY(ID_PERGUNTASECRETA) REFERENCES 
    TCC_SHOW.TB_PERGUNTASECRETA(ID_PERGUNTASECRETA),
    CONSTRAINT TB_LOGIN_PK PRIMARY KEY(ID_LOGIN) ENABLE
);

--DROP TABLE TCC_SHOW.TB_FUNCAO;
CREATE TABLE TCC_SHOW.TB_FUNCAO(
    ID_FUNCAO INTEGER NOT NULL,
    FUNCAO VARCHAR2(40) NOT NULL,
    
    CONSTRAINT TB_FUNCAO_PK PRIMARY KEY(ID_FUNCAO) ENABLE
);

--DROP TABLE TCC_SHOW.TB_FUNCIONARIO;
CREATE TABLE TCC_SHOW.TB_FUNCIONARIO(
    ID_FUNC INTEGER NOT NULL,
    ID_FUNCAO INTEGER NOT NULL,
    ID_ENDERECO INTEGER,
    ID_PESSOA INTEGER NOT NULL,
    CPF VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(120),
    TELEFONE VARCHAR2(14),
    
    CONSTRAINT CPF_FUNC_UN UNIQUE (CPF),
    CONSTRAINT TB_FUNC_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TCC_SHOW.TB_PESSOA(ID_PESSOA),
    CONSTRAINT TB_FUNC_ENDERECO_FK FOREIGN KEY (ID_ENDERECO)
    REFERENCES TCC_SHOW.TB_ENDERECO(ID_ENDERECO),
    CONSTRAINT TB_FUNCAO_FK FOREIGN KEY (ID_FUNCAO)
    REFERENCES TCC_SHOW.TB_FUNCAO(ID_FUNCAO),
    CONSTRAINT TB_FUNCIONARIO_PK PRIMARY KEY(ID_FUNC) ENABLE
);


--DROP TABLE TCC_SHOW.TB_PRECOS;
CREATE TABLE TCC_SHOW.TB_PRECOS(
    ID_SETOR INTEGER NOT NULL,
    ID_TIPO_ASSENTO INTEGER NOT NULL,
    PERC NUMBER(3),
    
    CONSTRAINT TB_PRECOS_PK PRIMARY KEY(ID_TIPO_ASSENTO, ID_SETOR) ENABLE
);