
/* DROP USER TCC_SHOW CASCADE;

CREATE USER TCC_SHOW IDENTIFIED BY "1234";

GRANT ALL PRIVILEGES to TCC_SHOW;*/


--DROP TABLE TB_TIPO_PESSOA;
CREATE TABLE TB_TIPO_PESSOA(
    ID_TIPO_PESSOA INTEGER NOT NULL,
    TIPO_PESSOA VARCHAR2(12) NOT NULL,
    
    CONSTRAINT TB_TIPO_PESSOA_PK PRIMARY KEY (ID_TIPO_PESSOA)
);

--DROP TABLE TB_PESSOA;
CREATE TABLE TB_PESSOA(
    ID_PESSOA INTEGER NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    DATA_NASC DATE,
    SEXO VARCHAR2(9) NOT NULL,
    ATIVO NUMBER(1) NOT NULL,
    ID_TIPO_PESSOA INTEGER NOT NULL,
    DATA_CRIACAO DATE,
    
    CONSTRAINT TB_PESSOA_PK PRIMARY KEY (ID_PESSOA),
    CONSTRAINT TB_TIPO_PESSOA_FK FOREIGN KEY(ID_TIPO_PESSOA)
    REFERENCES TB_TIPO_PESSOA(ID_TIPO_PESSOA)
);

--DROP TABLE TB_CEP;
CREATE TABLE TB_CEP(
    CEP VARCHAR2(8) NOT NULL,
    UF VARCHAR2(2),
    DESCRICAO VARCHAR2(256),
    CIDADE VARCHAR2(27),
    BAIRRO VARCHAR2(128),
    
    CONSTRAINT TB_CEP_PK PRIMARY KEY (CEP) ENABLE
);

--DROP TABLE TB_ENDERECO;
CREATE TABLE TB_ENDERECO(
    ID_ENDERECO INTEGER NOT NULL,
    CEP VARCHAR2(8),
    NUMERO NUMBER(6),
    COMPLEMENTO VARCHAR2(120),
    
    CONSTRAINT TB_ENDERECO_PK PRIMARY KEY (ID_ENDERECO),
    CONSTRAINT TB_CEP_FK FOREIGN KEY(CEP)
    REFERENCES TB_CEP(CEP)
);

--DROP TABLE TB_AGENTE;
CREATE TABLE TB_AGENTE(
    ID_AGENTE INTEGER NOT NULL,
    ID_ENDERECO INTEGER,
    TELEFONE VARCHAR2(14),
    TIPO_PESSOA VARCHAR2(8) NOT NULL,
    DOCUMENTO VARCHAR2(18),
    EMAIL VARCHAR2(120),
    NOME_PRINCIPAL VARCHAR2(120),
    NOME_SECUNDARIO VARCHAR2(120),
    ATIVO NUMBER(1),
    DATA_CRIACAO DATE,
    
    CONSTRAINT TB_AGENTE_PK PRIMARY KEY (ID_AGENTE) ENABLE,
    CONSTRAINT TB_AGENTE_ENDERECO_FK FOREIGN KEY(ID_ENDERECO)
    REFERENCES TB_ENDERECO(ID_ENDERECO)
);

--DROP TABLE TB_REDESOCIAL;
CREATE TABLE TB_REDESOCIAL(
    ID_REDESOCIAL INTEGER NOT NULL,
    FACEBOOK VARCHAR2(120),
    TWITTER VARCHAR2(120),
    INSTAGRAM VARCHAR2(120),
    
    CONSTRAINT TB_REDESOCIAL_PK PRIMARY KEY(ID_REDESOCIAL) ENABLE
);   

--DROP TABLE TB_ARTISTA_GERAL;
CREATE TABLE TB_ARTISTA_GERAL(
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    ID_REDESOCIAL INTEGER,
    ID_PESSOA INTEGER NOT NULL,
    URL_IMG VARCHAR2(250),
    
    CONSTRAINT TB_ART_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TB_PESSOA(ID_PESSOA),
     CONSTRAINT TB_REDESOCIAL_FK FOREIGN KEY (ID_REDESOCIAL)
    REFERENCES TB_REDESOCIAL(ID_REDESOCIAL),
    CONSTRAINT TB_ARTISTA_GERAL_PK PRIMARY KEY (ID_ARTISTA_GERAL) ENABLE
);

--DROP TABLE TB_ARTISTA;
CREATE TABLE TB_ARTISTA(
    ID_AGENTE INTEGER NOT NULL,
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    
    CONSTRAINT TB_ARTISTA_PK PRIMARY KEY (ID_ARTISTA_GERAL, ID_AGENTE) ENABLE
);

--DROP TABLE TB_ARTISTA_FIXO;
CREATE TABLE TB_ARTISTA_FIXO(
    ID_ARTISTA_GERAL INTEGER NOT NULL,
    ID_ENDERECO INTEGER NOT NULL,
    TELEFONE VARCHAR2(14),
    CPF VARCHAR2(12),
    EMAIL VARCHAR2(120),

    CONSTRAINT TB_ARTISTA_FIXO_PK PRIMARY KEY (ID_ARTISTA_GERAL, ID_ENDERECO) ENABLE
);

--DROP TABLE TB_FORMA_PAGAMENTO;
CREATE TABLE TB_FORMA_PAGAMENTO(
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    FORMA_PAGAMENTO VARCHAR2(30) NOT NULL,
    
    CONSTRAINT TB_FORMA_PAGAMENTO_PK PRIMARY KEY(ID_FORMA_PAGAMENTO) ENABLE
);

--DROP TABLE TB_DATA_CONTA;
CREATE TABLE TB_DATA_CONTA(
    ID_DATA_CONTA INTEGER NOT NULL,
    DATA_CONTA DATE,
    TIPO_DATA VARCHAR(11) NOT NULL,
    
    CONSTRAINT TB_DATA_CONTA_PK PRIMARY KEY (ID_DATA_CONTA)
);

--DROP TABLE TB_CONTAS;
CREATE TABLE TB_CONTAS(
    ID_CONTAS INTEGER NOT NULL,
    ID_DATA_CONTA INTEGER NOT NULL,
    TIPO_CONTA VARCHAR2(15),
    DATA_LANCAMENTO DATE,
    DATA_ENTREGUE DATE,
    DESCRICAO VARCHAR2(220),
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    SITUACAO VARCHAR(30),
    DEPARTAMENTO VARCHAR(30),
    VALOR NUMBER(24,2),
    ATIVO NUMBER(1),
    
    CONSTRAINT TB_CONTAS_PK PRIMARY KEY (ID_CONTAS),
    CONSTRAINT TB_FORMA_PAG_FK FOREIGN KEY(ID_FORMA_PAGAMENTO)
    REFERENCES TB_FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO),
    CONSTRAINT TB_DATA_CONTA_FK FOREIGN KEY(ID_DATA_CONTA)
    REFERENCES TB_DATA_CONTA(ID_DATA_CONTA)
);



--DROP TABLE TB_CLIENTE;
CREATE TABLE TB_CLIENTE(
    ID_CLIENTE INTEGER NOT NULL,
    CPF VARCHAR2(12),
    ID_PESSOA INTEGER NOT NULL,
    
    CONSTRAINT TB_CLIENTE_PK PRIMARY KEY (ID_CLIENTE) ENABLE,
    CONSTRAINT TB_CLI_PESSOA_FK FOREIGN KEY(ID_PESSOA) REFERENCES 
    TB_PESSOA(ID_PESSOA)
);

--DROP TABLE TB_TIPO_ASSENTO;
CREATE TABLE TB_TIPO_ASSENTO(
    ID_TIPO_ASSENTO NUMBER(4) NOT NULL,
    TIPO_ASSENTO VARCHAR2(8),
    
    CONSTRAINT TB_TIPO_ASSENTO_PK PRIMARY KEY (ID_TIPO_ASSENTO) ENABLE
);

--DROP TABLE TB_SETOR;
CREATE TABLE TB_SETOR(
    ID_SETOR INTEGER NOT NULL,
    SETOR VARCHAR2(6),
    
    CONSTRAINT TB_SETOR_PK PRIMARY KEY (ID_SETOR) ENABLE
);

--DROP TABLE TB_ASSENTO;
CREATE TABLE TB_ASSENTO(
    ID_ASSENTO INTEGER NOT NULL,
    ASSENTO_NUMER NUMBER(3) NOT NULL,
    ASSENTO_FILEIRA VARCHAR2(1) NOT NULL,
    ID_TIPO_ASSENTO INTEGER NOT NULL,
    ID_SETOR INTEGER NOT NULL,
    
    CONSTRAINT TB_ASSENTO_PK PRIMARY KEY (ID_ASSENTO) ENABLE,
    CONSTRAINT TB_SETOR_FK FOREIGN KEY(ID_SETOR) REFERENCES 
    TB_SETOR(ID_SETOR),
    CONSTRAINT TB_TIPO_ASSENTO_FK FOREIGN KEY(ID_TIPO_ASSENTO) REFERENCES 
    TB_TIPO_ASSENTO(ID_TIPO_ASSENTO)
);


--DROP TABLE TB_ASSENTO_CLI;
CREATE TABLE TB_ASSENTO_CLI(
    ID_ASSENTO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    ID_EVENTO INTEGER NOT NULL,
    
    CONSTRAINT TB_ASSENTO_CLI_PK PRIMARY KEY (ID_ASSENTO,ID_CLIENTE,ID_EVENTO) ENABLE
);

DROP TABLE TB_EVENTO;
CREATE TABLE TB_EVENTO(
    ID_EVENTO INTEGER NOT NULL,
    TITULO VARCHAR2(20),
    DATA_EVENTO DATE,
    DESCRICAO VARCHAR2(141),
    HORARIO_INICIO DATE,
    HORARIO_FINAL DATE,
    N_ARTISTAS NUMBER(3),
    TIPO_PAG VARCHAR2(20),
    ATIVO NUMBER(1) NOT NULL,
    VALOR_EVENTO NUMBER(10,2),
    
    CONSTRAINT TB_EVENTO_PK PRIMARY KEY(ID_EVENTO) ENABLE
);

--DROP TABLE TB_EVENTO_INGRESSO;
CREATE TABLE TB_EVENTO_INGRESSO(
    ID_EI INTEGER NOT NULL,
    PRECO_TOTAL NUMBER(15,2),
    ID_EVENTO INTEGER,
    ID_PAGAMENTO INTEGER,
    DESCONTO NUMBER(10,2),
    
    CONSTRAINT TB_EVENTOINGRESSO_PK PRIMARY KEY (ID_EI) ENABLE,
    CONSTRAINT TB_EVENTOINGRESSO_FK FOREIGN KEY (ID_EI)
    REFERENCES TB_EVENTO(ID_EVENTO)
    
);

--DROP TABLE TB_VENDA_INGRESSO;
CREATE TABLE TB_VENDA_INGRESSO(
    ID_VENDA INTEGER NOT NULL,
    ID_PESSOA INTEGER,
    DATAVENDA DATE,
    
    CONSTRAINT TB_VENDA_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TB_PESSOA(ID_PESSOA),
    CONSTRAINT TB_VENDA_INGRESSO_PK PRIMARY KEY (ID_VENDA) ENABLE
);

--DROP TABLE TB_ITEM_VENDA;
CREATE TABLE TB_ITEM_VENDA(
    ID_ITEM_VENDA INTEGER NOT NULL,
    ID_VENDA INTEGER,
    ID_EI INTEGER,
    ID_ASSENTO INTEGER,
    
    CONSTRAINT TB_ITEM_VENDA_PK PRIMARY KEY (ID_ITEM_VENDA) ENABLE,
    CONSTRAINT TB_VENDA_FK FOREIGN KEY (ID_VENDA) REFERENCES TB_VENDA_INGRESSO(ID_VENDA),
    CONSTRAINT TB_EI_FK FOREIGN KEY (ID_EI) REFERENCES TB_EVENTO_INGRESSO(ID_EI)
);



--DROP TABLE TB_PAGAMENTO;
CREATE TABLE TB_PAGAMENTO(
    ID_PAGAMENTO INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER,
    QUANTIA NUMBER(10,2),
    
    CONSTRAINT TB_PAGAMENTO_PK PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT TB_PAGAMENTO_FK FOREIGN KEY(ID_PAGAMENTO) REFERENCES 
    TB_FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO) 
);



--DROP TABLE TB_EVENTO_ARTISTA;
CREATE TABLE TB_EVENTO_ARTISTA(
    ID_EVENTO INTEGER NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    
    CONSTRAINT TB_EVENTO_PESSOA_PK PRIMARY KEY (ID_EVENTO,ID_PESSOA)
);

--DROP TABLE TB_PERGUNTASECRETA;
CREATE TABLE TB_PERGUNTASECRETA(
    ID_PERGUNTASECRETA INTEGER NOT NULL,
    DESCRICAO VARCHAR2(128),
    RESPOSTA VARCHAR2(120),
    
    CONSTRAINT TB_PERGUNTASECRETA_PK PRIMARY KEY(ID_PERGUNTASECRETA) ENABLE
);

--DROP TABLE TB_NIVELACESSO;
CREATE TABLE TB_NIVELACESSO(
    ID_NIVELACESSO INTEGER NOT NULL,
    NIVELACESSO VARCHAR2(20),
    
    CONSTRAINT TB_NIVELACESSO_PK PRIMARY KEY (ID_NIVELACESSO) ENABLE
);


--DROP TABLE TB_LOGIN;
CREATE TABLE TB_LOGIN(
    ID_LOGIN INTEGER NOT NULL,
    ID_NIVELACESSO INTEGER NOT NULL,
    ID_PERGUNTASECRETA INTEGER NOT NULL,
    USUARIO VARCHAR2(50) NOT NULL,
    SENHA VARCHAR2(50) NOT NULL,
    DATAULTIMOACESSO DATE,
    ID_PESSOA INTEGER NOT NULL,
    
    CONSTRAINT TB_NIVEL_ACESSO_FK FOREIGN KEY (ID_NIVELACESSO)
    REFERENCES TB_NIVELACESSO(ID_NIVELACESSO),
    CONSTRAINT TB_PERGUNTASECRETA_FK FOREIGN KEY(ID_PERGUNTASECRETA) REFERENCES 
    TB_PERGUNTASECRETA(ID_PERGUNTASECRETA),
    CONSTRAINT TB_LOGIN_PK PRIMARY KEY(ID_LOGIN) ENABLE
);

--DROP TABLE TB_FUNCAO;
CREATE TABLE TB_FUNCAO(
    ID_FUNCAO INTEGER NOT NULL,
    FUNCAO VARCHAR2(40) NOT NULL,
    
    CONSTRAINT TB_FUNCAO_PK PRIMARY KEY(ID_FUNCAO) ENABLE
);

--DROP TABLE TB_FUNCIONARIO;
CREATE TABLE TB_FUNCIONARIO(
    ID_FUNC INTEGER NOT NULL,
    ID_FUNCAO INTEGER NOT NULL,
    ID_ENDERECO INTEGER,
    ID_PESSOA INTEGER NOT NULL,
    CPF VARCHAR2(12),
    EMAIL VARCHAR2(120),
    TELEFONE VARCHAR2(14),
    
    CONSTRAINT TB_FUNC_PESSOA_FK FOREIGN KEY (ID_PESSOA)
    REFERENCES TB_PESSOA(ID_PESSOA),
    CONSTRAINT TB_FUNC_ENDERECO_FK FOREIGN KEY (ID_ENDERECO)
    REFERENCES TB_ENDERECO(ID_ENDERECO),
    CONSTRAINT TB_FUNCAO_FK FOREIGN KEY (ID_FUNCAO)
    REFERENCES TB_FUNCAO(ID_FUNCAO),
    CONSTRAINT TB_FUNCIONARIO_PK PRIMARY KEY(ID_FUNC) ENABLE
);


--DROP TABLE TB_PRECOS;
CREATE TABLE TB_PRECOS(
    ID_SETOR INTEGER NOT NULL,
    ID_TIPO_ASSENTO INTEGER NOT NULL,
    PERC NUMBER(3),
    
    CONSTRAINT TB_PRECOS_PK PRIMARY KEY(ID_TIPO_ASSENTO, ID_SETOR) ENABLE
);
--DROP TABLE TB_BANNER;
CREATE TABLE TB_BANNER(
    ID_BANNER INTEGER NOT NULL,
    URL_IMG VARCHAR2(250),
    URL_PAG VARCHAR2(250),
    ATIVO NUMBER(1),
    
    CONSTRAINT TB_BANNER_PK PRIMARY KEY(ID_BANNER)
);

DROP TABLE TB_DESCONTOS;
CREATE TABLE TB_DESCONTOS(
    ID_DESCONTO INTEGER NOT NULL,
    DESCONTO NUMBER(5,1),
    COD_PROMOCIONAL VARCHAR2(20),
    ATIVO NUMBER(1),
    
    CONSTRAINT TB_DESCONTOS_PK PRIMARY KEY(ID_DESCONTO)
);

CREATE TABLE TB_DESCONTOS_CLIENTE(
    ID_DESCONTO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    
    CONSTRAINT TB_DESCONTOS_CLIENTE_PK PRIMARY KEY(ID_DESCONTO, ID_CLIENTE)
);

CREATE TABLE TB_TIPO_LOG(
ID_TIPO_LOG INTEGER NOT NULL,
TIPO_LOG VARCHAR2(15),

CONSTRAINT TB_TIPO_LOG PRIMARY KEY(ID_TIPO_LOG)
);

--DROP TABLE TB_LOG;
CREATE TABLE TB_LOG(
ID_LOG INTEGER NOT NULL,
DATA_LOG DATE,
ID_TIPO_LOG INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,

CONSTRAINT TB_LOG PRIMARY KEY(ID_LOG),
CONSTRAINT TB_TIPO_LOG_FK FOREIGN KEY (ID_TIPO_LOG)
    REFERENCES TB_TIPO_LOG(ID_TIPO_LOG),
CONSTRAINT TB_USUARIO_FK FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_TABELAS_LOG(
ID_TABELA_LOG INTEGER NOT NULL,
TABELA VARCHAR2(15),
TABELA_APELIDO VARCHAR2(15),

CONSTRAINT TB_TABELA_LOG PRIMARY KEY(ID_TABELA_LOG)
);

CREATE TABLE TB_LOG_INSERCAO(
ID_LOG_INSER INTEGER NOT NULL,
ID_LOG INTEGER NOT NULL,
ID_TABELA_LOG INTEGER NOT NULL,
ID_INSERIDO INTEGER NOT NULL,

CONSTRAINT TB_LOG_INSERCAO PRIMARY KEY(ID_LOG_INSER),
CONSTRAINT TB_LOG_INSER_FK FOREIGN KEY (ID_LOG)
    REFERENCES TB_LOG(ID_LOG),
CONSTRAINT TABELA_LOG_INSER_FK FOREIGN KEY (ID_TABELA_LOG)
    REFERENCES TB_TABELAS_LOG(ID_TABELA_LOG)
);

CREATE TABLE TB_LOG_EXCLUSAO(
ID_LOG_EXCL INTEGER NOT NULL,
ID_LOG INTEGER NOT NULL,
ID_TABELA_LOG INTEGER NOT NULL,
ID_EXCLUIDO INTEGER NOT NULL,

CONSTRAINT TB_LOG_EXCLUSAO PRIMARY KEY(ID_LOG_EXCL),
CONSTRAINT TB_LOG_EXCL_FK FOREIGN KEY (ID_LOG)
    REFERENCES TB_LOG(ID_LOG),
CONSTRAINT TABELA_LOG_EXCL_FK FOREIGN KEY (ID_TABELA_LOG)
    REFERENCES TB_TABELAS_LOG(ID_TABELA_LOG)
);

CREATE TABLE TB_LOG_ALTERACAO(
ID_LOG_ALTER INTEGER NOT NULL,
ID_LOG INTEGER NOT NULL,
ID_TABELA_LOG INTEGER NOT NULL,
ID_ALTERADO INTEGER NOT NULL,

CONSTRAINT TB_LOG_ALTERACAO PRIMARY KEY(ID_LOG_ALTER),
CONSTRAINT TB_LOG_ALTER_FK FOREIGN KEY (ID_LOG)
    REFERENCES TB_LOG(ID_LOG),
CONSTRAINT TABELA_LOG_ALTER_FK FOREIGN KEY (ID_TABELA_LOG)
    REFERENCES TB_TABELAS_LOG(ID_TABELA_LOG)
);
